export const table = {
  header: [
    {
      header_name: "s.no",
      template_name: "sno",
    },
    {
      header_name: "Name",
      template_name: "name",
    },
    {
      header_name: "Age",
      template_name: "age",
    },
    {
      header_name: "Gender",
      template_name: "gender",
    },
    {
      header_name: "Designation",
      template_name: "designation",
    },
  ],
  body: [
    {
      sno: 1,
      name: "Eswaramoorthy karthikeyan",
      age: 25,
      gender: "Male",
      designation: "Developer",
    },
    {
      sno: 2,
      name: "Gopinath",
      age: 24,
      gender: "Male",
      designation: "CTO",
    },
    {
      sno: 3,
      name: "Allen paul",
      age: 25,
      gender: "Male",
      designation: "CEO",
    },
    {
      sno: 4,
      name: "Jefferson Swartz",
      age: 25,
      gender: "Male",
      designation: "CCO",
    },
    {
      sno: 5,
      name: "Eswaramoorthy karthikeyan",
      age: 25,
      gender: "Male",
      designation: "Developer",
    },
    {
      sno: 6,
      name: "Gopinath",
      age: 24,
      gender: "Male",
      designation: "CTO",
    },
    {
      sno: 7,
      name: "Allen paul",
      age: 25,
      gender: "Male",
      designation: "CEO",
    },
    {
      sno: 8,
      name: "Jefferson Swartz",
      age: 25,
      gender: "Male",
      designation: "CCO",
    },
    {
      sno: 9,
      name: "Gopinath",
      age: 24,
      gender: "Male",
      designation: "CTO",
    },
    {
      sno: 10,
      name: "Allen paul",
      age: 25,
      gender: "Male",
      designation: "CEO",
    },
    {
      sno: 11,
      name: "Jefferson Swartz",
      age: 25,
      gender: "Male",
      designation: "CCO",
    },
  ],
  itemsPerPage: 2,
  currentPage: 1,
  defaultSort: 0,
}
