export const table = {
  header: [
    {
      header_name: "s.no",
      template_name: "sno",
    },
    {
      header_name: "Name",
      template_name: "name",
    },
    {
      header_name: "Age",
      template_name: "age",
    },
    {
      header_name: "Gender",
      template_name: "gender",
    },
    {
      header_name: "Designation",
      template_name: "designation",
    },
    {
      header_name: "Action",
      template_name: "action",
      type: "action",
    },
  ],
  body: [
    {
      action_val: 1,
      sno: 1,
      name: "Eswaramoorthy karthikeyan",
      age: 25,
      gender: "Male",
      designation: "Developer",
      action: ["view", "edit", "delete"],
    },
    {
      action_val: 2,
      sno: 2,
      name: "Gopinath",
      age: 24,
      gender: "Male",
      designation: "CTO",
      action: ["view", "edit", "delete"],
    },
    {
      action_val: 3,
      sno: 3,
      name: "Allen paul",
      age: 25,
      gender: "Male",
      designation: "CEO",
      action: ["view", "edit", "delete"],
    },
    {
      action_val: 4,
      sno: 4,
      name: "Jefferson Swartz",
      age: 25,
      gender: "Male",
      designation: "CCO",
      action: ["view", "edit", "delete"],
    },
    {
      action_val: 5,
      sno: 5,
      name: "Eswaramoorthy karthikeyan",
      age: 25,
      gender: "Male",
      designation: "Developer",
      action: ["view", "edit", "delete"],
    },
    {
      action_val: 6,
      sno: 6,
      name: "Gopinath",
      age: 24,
      gender: "Male",
      designation: "CTO",
      action: ["view", "edit", "delete"],
    },
    {
      action_val: 7,
      sno: 7,
      name: "Allen paul",
      age: 25,
      gender: "Male",
      designation: "CEO",
      action: ["view", "edit", "delete"],
    },
    {
      action_val: 8,
      sno: 8,
      name: "Jefferson Swartz",
      age: 25,
      gender: "Male",
      designation: "CCO",
      action: ["view", "edit", "delete"],
    },
    {
      action_val: 9,
      sno: 9,
      name: "Gopinath",
      age: 24,
      gender: "Male",
      designation: "CTO",
      action: ["view", "edit", "delete"],
    },
    {
      action_val: 10,
      sno: 10,
      name: "Allen paul",
      age: 25,
      gender: "Male",
      designation: "CEO",
      action: ["view", "edit", "delete"],
    },
    {
      action_val: 11,
      sno: 11,
      name: "Jefferson Swartz",
      age: 25,
      gender: "Male",
      designation: "CCO",
      action: ["view", "edit", "delete"],
    },
  ],
  itemsPerPage: 2,
  currentPage: 1,
  defaultSort: 0,
  actionIndex: "action_val",
}
